image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - golang.go
tasks:
  - name: Tailscale
    before: service tailscaled start
ports:
  - port: 1055
    onOpen: ignore
  - port: 1080
    onOpen: ignore
